import { EventItem } from '@/types';

export const sampleEvents: EventItem[] = [
  {
    id: 'night-romashka-main',
    title: 'Ніч Ромашки',
    date: '2026-08-07',
    displayDate: '07 Серпня 2026',
    time: '22:00 – 06:00',
    category: 'parties',
    musicGenre: 'Peak Time Techno / Synthpop / Eurodance',
    artists: ['DJ Bloom', 'Resident Alex', 'Special Guest Star'],
    priceFrom: 350,
    currency: 'UAH',
    ageLimit: '18+',
    status: 'available',
    posterUrl: '/images/hero-poster.png',
    isFeatured: true,
    description:
      'Головна п’ятнична вечірка клубу «Ромашка». Ніч неймовірної світлової енергії, неонового диму, свіжої електронної музики та абсолютної свободи самовираження. Зустріч до світанку в колі своїх.',
    timetable: [
      { time: '22:00', activity: 'Doors Open & Lounge Ambient Warmup', artist: 'Resident Alex' },
      { time: '00:00', activity: 'Main Stage Peak Time Set', artist: 'DJ Bloom' },
      { time: '02:30', activity: 'Headline Eurodance & Synthpop Performance', artist: 'Special Guest Star' },
      { time: '04:30 – 06:00', activity: 'After-party Beats', artist: 'Resident Alex' },
    ],
    location: 'Головний зал «Ромашка», МІСТО',
    entryRules: [
      'Обов’язкова наявність оригіналу документа, що підтверджує вік (18+)',
      'Дотримання правил взаємної поваги та згоди',
      'Заборона на фото- та відеозйомку людей без їхньої згоди',
      'Охайний вигляд (Casual / Clubwear / Expressive)',
    ],
    refundPolicy: 'Повернення квитків можливе не пізніше ніж за 24 години до початку події через службу підтримки.',
  },
  {
    id: 'disco-bloom-01',
    title: 'Disco Bloom',
    date: '2026-08-08',
    displayDate: '08 Серпня 2026',
    time: '23:00 – 05:00',
    category: 'parties',
    musicGenre: 'Disco / Nu-Disco / House',
    artists: ['DJ Disco Queen', 'Groove Master'],
    priceFrom: 300,
    currency: 'UAH',
    ageLimit: '18+',
    status: 'few',
    posterUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80',
    description:
      'Яскравий вибух ретро-ритмів, дзеркальних куль та танцювального house. Вдягайте свої найкращі сяючі образи та поринайте у вайб 80-х і 90-х.',
    timetable: [
      { time: '23:00', activity: 'Nu-Disco Groove', artist: 'Groove Master' },
      { time: '01:30', activity: 'Classic Disco Hits & House Mix', artist: 'DJ Disco Queen' },
    ],
    location: 'Головний зал «Ромашка»',
    entryRules: ['18+ Контроль', 'Повага до особистого простору гостей'],
    refundPolicy: 'Повернення квитків за 24 години до початку.',
  },
  {
    id: 'drag-garden-show',
    title: 'Drag Garden',
    date: '2026-08-14',
    displayDate: '14 Серпня 2026',
    time: '21:30 – 04:00',
    category: 'drag',
    musicGenre: 'Pop / Drag Extravaganza / Live Vocal',
    artists: ['Queen Rose', 'Violet Velvet', 'La Diva Diva'],
    priceFrom: 400,
    currency: 'UAH',
    ageLimit: '18+',
    status: 'available',
    posterUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    description:
      'Незабутнє драг-шоу з яскравими костюмами, гумором, перформансами та живим вокалом. Кращі королеви сцени дарують вам ніч чарівного перевтілення.',
    timetable: [
      { time: '21:30', activity: 'Doors & Cocktail Hour', artist: 'DJ Warmup' },
      { time: '22:30', activity: 'Drag Show Part 1: Blooming Act', artist: 'Queen Rose & Violet Velvet' },
      { time: '00:00', activity: 'Drag Show Part 2: Main Extravaganza', artist: 'La Diva Diva' },
      { time: '01:30', activity: 'Queer Dance Party', artist: 'DJ Bloom' },
    ],
    location: 'Головна сцена «Ромашка»',
    entryRules: ['18+', 'Гучні аплодисменти та доброзичлива атмосфера вітаються!'],
    refundPolicy: 'Повернення квитків за 24 години.',
  },
  {
    id: 'queer-friday-dance',
    title: 'Queer Friday',
    date: '2026-08-21',
    displayDate: '21 Серпня 2026',
    time: '22:00 – 06:00',
    category: 'parties',
    musicGenre: 'Pop Anthems / House / LGBTQ+ Classic',
    artists: ['DJ Sparkle', 'Queer Beats'],
    priceFrom: 300,
    currency: 'UAH',
    ageLimit: '18+',
    status: 'available',
    posterUrl: 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?auto=format&fit=crop&w=1200&q=80',
    description:
      'Танцювальна п’ятниця без кордонів. Найулюбленіші гімни свободи, сучасна поп-музика та драйвовий хаус, під які неможливо встояти на місці.',
    timetable: [
      { time: '22:00', activity: 'Queer Beats Entrance', artist: 'Queer Beats' },
      { time: '01:00', activity: 'Pop Anthems Explosion', artist: 'DJ Sparkle' },
    ],
    location: 'Головний зал «Ромашка»',
    entryRules: ['18+ ID control', 'Zero tolerance to discrimination'],
    refundPolicy: 'Повернення квитків за 24 години.',
  },
  {
    id: 'after-dark-techno',
    title: 'After Dark',
    date: '2026-08-28',
    displayDate: '28 Серпня 2026',
    time: '23:59 – 07:00',
    category: 'special',
    musicGenre: 'Dark Techno / Hypnotic Beats / Industrial',
    artists: ['Shadow Project', 'Resident DJ Night'],
    priceFrom: 450,
    currency: 'UAH',
    ageLimit: '18+',
    status: 'few',
    posterUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1200&q=80',
    description:
      'Спеціальний формат для поціновувачів глибокого гіпнотичного техно та нічного диму. Простір занурюється у темряву, залишаючи тільки світло неону та потужний басс.',
    timetable: [
      { time: '00:00', activity: 'Hypnotic Induction', artist: 'Resident DJ Night' },
      { time: '02:30', activity: 'Dark Techno Headline Set', artist: 'Shadow Project' },
    ],
    location: 'Underground Sound Stage «Ромашка»',
    entryRules: ['18+', 'No Flash photography'],
    refundPolicy: 'Повернення квитків за 24 години.',
  },
  {
    id: 'sunday-recovery-lounge',
    title: 'Sunday Recovery',
    date: '2026-08-30',
    displayDate: '30 Серпня 2026',
    time: '19:00 – 01:00',
    category: 'special',
    musicGenre: 'Downtempo / Chillout / Deep Organic',
    artists: ['Ambient Soul', 'Tea & Beats'],
    priceFrom: 200,
    currency: 'UAH',
    ageLimit: '18+',
    status: 'available',
    posterUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
    description:
      'Затишний і спокійний недільний формат. Приємна музика, авторські коктейлі, м’яке світло та щирі розмови для відновлення сил перед новим тижнем.',
    timetable: [
      { time: '19:00', activity: 'Organic Warm Ambient', artist: 'Tea & Beats' },
      { time: '21:30', activity: 'Downtempo Lounge Session', artist: 'Ambient Soul' },
    ],
    location: 'Lounge Zone «Ромашка»',
    entryRules: ['18+', 'Relaxed vibe'],
    refundPolicy: 'Повернення квитків за 24 години.',
  },
];
